2025-01-19 11:36 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 91, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceData.download(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 43, in wrapper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 254, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 196, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 7094, in futures_klines
    return self._request_futures_api("get", "klines", data=params)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 109, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 75, in _request
    return self._handle_response(self.response)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 84, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2025-01-19 11:36 ERROR symbol = TUSDUSDT
2025-01-19 11:41 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 91, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceData.download(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 43, in wrapper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 254, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 196, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 7092, in futures_klines
    return self._request_futures_api("get", "klines", data=params)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 107, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 75, in _request
    return self._handle_response(self.response)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 84, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2025-01-19 11:41 ERROR symbol = TUSDUSDT
2025-01-19 11:43 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 91, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceData.download(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 43, in wrapper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 255, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 196, in minutes_of_new_data
    new = pd.to_datetime(client.futures_klines(symbol=symbol, interval=kline_size)[-1][0],
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 7092, in futures_klines
    return self._request_futures_api("get", "klines", data=params)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 107, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 75, in _request
    return self._handle_response(self.response)
  File "C:\Users\a046829713\Desktop\program\RLTrading\lib\site-packages\binance\client.py", line 84, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.

2025-01-19 11:43 ERROR symbol = TUSDUSDT
2025-01-19 11:45 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 91, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceData.download(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 43, in wrapper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 269, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 160, in historicalklines
    time.sleep(1)
KeyboardInterrupt

2025-01-19 11:45 ERROR symbol = IOTAUSDT
2025-01-19 12:24 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 91, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceData.download(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 43, in wrapper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 258, in download
    oldest_point, newest_point = cls.minutes_of_new_data(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 201, in minutes_of_new_data
    time.sleep(100)
KeyboardInterrupt

2025-01-19 12:24 ERROR symbol = BTCUSDT
